import Head from 'next/head'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

export default function Home() {
const HandleOnClick=()=>{
console.log('hello :>> ');
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Coffee connoisseur
        </h1> */}
        <Banner buttonText ='View stores nearby' handleOnclick={HandleOnClick}/>
      </main>
    </div>
  )
}
